### ISSUE TITLE
Can't enter any decimals

### ISSUE THREAD

**Issue by xuanmir** [lionsharecapital/lionshare.capital#6]
Are we expected to have only 1-2-3-4-5000-etc Bitcoins? This is absurd...

Other than that, congratulations for a very nice design.

**Comment by jenbennings** [comment]
The app supports decimal entry. Have you tried it or are you basing this off the image on the marketing page?

**Comment by xuanmir** [comment]
Of course I tried it. Actually, I just found out that it does work, but when you're hovering above the quantity it displays a tooltip that says "Please enter a valid value. The two nearest valid values are 0 and 1." So everything works correctly, just that there's an error message which shouldn't exist. :)

**Comment by jenbennings** [comment]
Thanks for clarifying. I've made an issue on the repo for the desktop app (https://github.com/lionsharecapital/lionshare-desktop/issues/41).
